### ISSUE TITLE
Option to specify output file name

### ISSUE THREAD

**Issue by weslambert** [jamf/aftermath#35]
Hi! Thanks for all of your great work on this project!

Is there currently an option to specify the output file name? I saw the option for the output directory, but was just curious. If not, would this be something that could be considered as an option for the future?

Thanks!

**Comment by stuartjash** [comment]
There currently is not a way to specify the name of the file output, only the output location, but I love the idea!

**Comment by mattbenyo** [comment]
updated in v1.2.0
