### ISSUE TITLE
Single binary release format

### ISSUE THREAD

**Issue by weslambert** [jamf/aftermath#36]
Hi! Thanks for all of your great work on this project!

Would it be possible to have a single binary release, in addition to the existing release format?

Thanks!

**Comment by weslambert** [comment]
Correct, it would be nice to have it outside of the `pkg`.

**Comment by stuartjash** [comment]
So a release looking like
```
Aftermath.pkg
AftermathUninstaller.pkg
aftermath_binary
source_code
```
Would that solve what you're trying to do?

**Comment by weslambert** [comment]
Yes, that would be ideal. Thank you!

**Comment by stuartjash** [comment]
Updated in[ v1.1.0 release](https://github.com/jamf/aftermath/releases/tag/v1.1.0)

**Comment by weslambert** [comment]
Awesome, thanks! I'll go ahead and close this issue.
