### ISSUE TITLE
quotation(message: "Can\'t have non-quote here: F")

### ISSUE THREAD

**Issue by evild3ad** [jamf/aftermath#38]
Hi! Thanks for releasing Aftermath!

Analyzing the Aftermath archive (created with Aftermath.pkg) is crashing with following error message:

```
2022-10-07T12:35:02Z - Timeline.swift - Parsing metadata...  
quotation(message: "Can\'t have non-quote here: F")   
```

temp_timeline.csv has 0 byte.

**Comment by pvieito** [comment]
Same here:

```
2022-10-13T22:29:32Z - Timeline.swift - Parsing metadata...
quotation(message: "Can\'t have non-quote here: v")
```

**Comment by stuartjash** [comment]
Thanks everyone. I think this is an issue in a dependency. Will look into it. Thank you all for the feedback!

**Comment by mattbenyo** [comment]
updated in v1.2.0

**Comment by evild3ad** [comment]
Works! Thank you!
