### ISSUE TITLE
upload results to cloud

### ISSUE THREAD

**Issue by shopaholic0531** [jamf/aftermath#43]
Hi team. Is there a way that you could suggest if a script exists in aftermath to upload the .zip file to a bucket for admins to look at? 
I am having trouble finding it.
Thank you

**Comment by stuartjash** [comment]
There is no official built-in functionality to aftermath to do that yet, however, some of the geniuses at Jamf wrote some great ones. Let me know if this fits your needs.
[](https://github.com/jamf/jamfprotect/tree/main/soar_playbooks/aftermath_collection)
