### ISSUE TITLE
Unpacking Aftermath archives: CRC Failed

### ISSUE THREAD

**Issue by evild3ad** [jamf/aftermath#46]
Both Aftermath archives (Collection and Analysis) created by v1.2.0 are corrupt. I get CRC errors when extracting files with Keka.

Same with 7-Zip.
`7z t Aftermath_C02X95WFJGH6.zip`

```
ERROR: CRC Failed : Aftermath_C02X95WFJGH6/Artifacts/raw/logs/system_logs/install.log
ERROR: CRC Failed : Aftermath_C02X95WFJGH6/metadata.csv 
```
```
ERROR: CRC Failed : Aftermath_Analysis_C02X95WFJGH6/logs.csv
ERROR: CRC Failed : Aftermath_Analysis_C02X95WFJGH6/storyline.csv
```

**Comment by stuartjash** [comment]
I'll take a look at this. I'm not having any issue unzipping using either double-clicking the zip file or using the `unzip` command, but I saw the same error just now with using 7zip. Do you know if you had this issue before v1.2.0? @evild3ad

**Comment by evild3ad** [comment]
@stuartjash Unpacking the archives in v1.0.0 and v1.1.0 worked fine (Collection only).

**Comment by stuartjash** [comment]
I'm seeing the issue also on v1.1.0 and v1.0.0. I'll work on finding a fix.

**Comment by evild3ad** [comment]
Hm...possible...I used a very old version of Keka and upgraded mid of November...so after the releases of v1.0.0 and v1.1.0.

Thank you!
