### ISSUE TITLE
error building on  10.15.7

### ISSUE THREAD

**Issue by th-sid1** [jamf/aftermath#52]
Downloaded from master branch, but i get following error while building ... appreciate any clue

```
error: No signing certificate "Developer ID Application" found: No "Developer ID Application" signing certificate matching team ID "6PV5YF2UES" with a private key was found. (in target 'aftermath' from project 'aftermath')
```

**Comment by stuartjash** [comment]
what is the command you use when building? The one from the readme?

**Comment by th-sid1** [comment]
correct `xcodebuild -scheme "aftermath"`

**Comment by stuartjash** [comment]
As of right now, aftermath only provides full support for macOS 12 and above.
