### ISSUE TITLE
No signed and notarized pkg for Release 2.0.0

### ISSUE THREAD

**Issue by built2order** [jamf/aftermath#55]
Project README suggests that there is a Aftermath.pkg available under [Releases](https://github.com/jamf/aftermath/releases) however only archives of source code are available for this version. If this is a build error, can a build status be added to the project home page to allow the community to contribute?

**Comment by loke-ss** [comment]
This is impacting me too. i'm using installomator to install aftermath and its failing because the pkg for 2.0 isn't available.

**Comment by stuartjash** [comment]
There should now be a 2.0 pkg available. Sorry for the delay and inconvenience.

**Comment by loke-ss** [comment]
Thanks Stuart. it worked for me.
