### ISSUE TITLE
Package version is set '0'

### ISSUE THREAD

**Issue by scriptingosx** [jamf/aftermath#56]
The package version metadata for those release that exist (2.0 is missing a package, #55) is set to '0.' This not only confuse tools that rely on that metadata, such as autopkg or Installomator, but might confuse the macOS installation system, which might decide that since the package version has not changed, it doesn't need to re-install the package and change no files on the system.

You should set the package version with `pkgbuild`'s `--version` option to the release version.

**Comment by golbiga** [comment]
This was addressed in 2.2.1.
