### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by abrownsyn** [jamf/aftermath#63]
We trying to create build i'm receiving the following error:

error: No signing certificate "Developer ID Application" found: No "Developer ID Application" signing certificate matching team ID "C793NB2B2B" with a private key was found. (in target 'aftermath' from project 'aftermath')

**Comment by golbiga** [comment]
You will need to switch to your dev certificate or set to none/sign to run locally.

https://developer.apple.com/documentation/xcode/preparing-your-app-for-distribution/
